### ISSUE TITLE
Occurance between dates

### ISSUE THREAD

**Issue by ch33foong** [pbogut/recurring_events#12]
Hi there,

Correct me if I am wrong you can only take a specific number of events after a date. Is it possible to query all events between 2 dates?

**Comment by pbogut** [comment]
You can use `until` to limit to specific date. Start date will be your date, if your rule requires different date then I guess you would have to reduce result yourself with `Enum.drop_while/2`

**Comment by ch33foong** [comment]
I am so sorry, I only realised there is a :until filter after I looked at the tests.

Thanks for your reply :)
