### ISSUE TITLE
new release?

### ISSUE THREAD

**Issue by bgentry** [pbogut/recurring_events#13]
Hi there, thanks for creating this package!

The latest released version (v0.3.0) contains some warnings on newer Elixir versions:

```
warning: clauses for the same defp should be grouped together, defp by_set_position/2 was previously defined (lib/recurring_events.ex:160)
  lib/recurring_events.ex:172
```

These appear to be fixed on `master`. Any chance you could publish a new version of this package so we can run off a published version? Thanks! :pray:

**Comment by pbogut** [comment]
Thanks for using it. I've just released 0.4.0.

**Comment by bgentry** [comment]
@pbogut could you also push this tag to GitHub? thank you!

**Comment by pbogut** [comment]
Apparently forgot about it, sorry, its pushed now.
