### ISSUE TITLE
Some invalid values passed to `take/[2,3]` will crash the VM

### ISSUE THREAD

**Issue by voughtdq** [pbogut/recurring_events#17]
When giving a negative value to `take/[2,3]` like this:

```
RecurringEvents.take(Date.utc_today(), %{by_day: :monday, freq: :weekly}, -1)
```

The function will consume resources until it crashes the VM. 

The same goes for some invalid values, for example:

```
RecurringEvents.take(Date.utc_today(), %{by_day: :m, freq: :weekly}, 3)
```

It's probably best to raise an exception when bad values are provided.

**Comment by pbogut** [comment]
Fixed in #18
