### ISSUE TITLE
Support for until rule

### ISSUE THREAD

**Issue by tlvenn** [pbogut/recurring_events#3]
Hi,

Awesome library, I was lamenting over the lack of a good RRULE library in Elixir land and stumble upon yours.

Would you consider adding support for the until rule ?

Thanks in advance.

**Comment by tlvenn** [comment]
Was looking at the code and noticed that until rule is actually already supported
> https://github.com/pbogut/recurring_events/blob/master/lib/recurring_events.ex#L131

Closing the issue.

**Comment by pbogut** [comment]
Thanks. I didn't notice its missing form the doc, will have to add it.
